#!/bin/bash
# Exécute les tests JavaScript dans le dépôt Transp
name: Run Tests
exclude:
  - 'v2.3.md'
  - 'smoke.md'
  - 'v2.2.md'
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm install --production
        working-directory: ./tests
      
      - name: Run all tests
        run: bash .github/scripts/run-tests.sh